### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by peter279k** [RaggiTech/php-dot-array#2]
To let all behaviors be verified or correct, it would be great to add unit tests.

**Comment by RaggiTech** [comment]
@peter279k will work on this point as soon as possible . <3

**Comment by peter279k** [comment]
@RaggiTech, if having any help, I can help you to work on this :).

**Comment by RaggiTech** [comment]
@peter279k 
Really it gonna be my pleasure if you can fork this repo and add unit tests then pull request. if you have enough time to do that.
thank you so much <3

**Comment by RaggiTech** [comment]
@peter279k Please, can you check the current tests before i release a new version with it?

**Comment by peter279k** [comment]
It seems that this package use `orchestra/testbench` package to accomplish this issue.

As far as I know, this `orchestra/testbench` package is for testing Laravel service provider.

It seems that this package is not part of Laravel service provider and I think it will be great to use `phpunit/phpunit` package instead directly :).

**Comment by RaggiTech** [comment]
@peter279k done ;)

**Comment by peter279k** [comment]
@RaggiTech, thanks for your reply.

I think you misunderstand what I mean, but don't be worried about that :).

I've create related PR to resolve this issue and some improvements about these tests.

Feel free to review and merge PR.

Once this PR is merged, I think we can release new version and resolve this issue now :smile:.

**Comment by RaggiTech** [comment]
@peter279k **merged ;)**

**Comment by peter279k** [comment]
Closed via PR #3 :).
