### ISSUE TITLE
Integrate CI building service

### ISSUE THREAD

**Issue by peter279k** [RaggiTech/php-dot-array#4]
As title, to make upcoming commits automatic to be verified, it should consider integrating CI building services.

If we don't have special preferences, I think we can consider using GitHub Action to resolve this issue.

@RaggiTech, what do you think about that?

Once this issue is accepted by repository owner, I will be happy to work on this :).

**Comment by RaggiTech** [comment]
@peter279k let's do what you think it's better for this repository. so tell me how can i help you 
<3 :)

**Comment by peter279k** [comment]
@RaggiTech, thanks for your reply and concern :).

I've created related PR to resolve this issue.

Once this PR is merged, the GitHub Action will check upcoming commits and PRs.

**Comment by peter279k** [comment]
Closed via PR #6.
